[build]
  command = "pnpm build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "pnpm dev"
  targetPort = 4321

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 